import { useState } from 'react'
import Head from 'next/head'
import Heart from '@react-sandbox/heart'

export default function Home() {
  const [active, setActive] = useState(false)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <Heart
          width={84}
          height={84}
          active={active}
          onClick={() => setActive(!active)}
        />
      </main>
    </>
  )
}
